config/routes.rb
AuthTest::Application.routes.draw do
  devise_for :users

  match '/secret', :to => 'pages#secret'

  root :to => "pages#home"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :rpx_connectable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :authenticate_user!, :except => [:home]
	
  def home
  end
  
  def secret
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>AuthTest</title>
		<!--[if lt IE 9]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
		<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
		<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
		<%= stylesheet_link_tag 'custom', :media => 'screen' %>
		<%= javascript_include_tag :defaults %>
		<%= csrf_meta_tag %>
	</head>
	<body>
		<div class="container">
			<header>
				<nav>
					<ul>
						<li>
							<% if user_signed_in? %>
							Signed in as<%= link_to current_user.email, root_path %><%= link_to "Sign out", destroy_user_session_path %>
							<% else %>
							<%= link_to_rpx "Sign in", user_session_url %>
							<% end %>
						</li>
					</ul>
				</nav>
			</header>
			<section>
				<% flash.each do |key, value| %>
				<%= content_tag(:div, value, :class => "flash #{key}") %>
				<% end %>
				<%= yield %>
			</section>
			<footer>
				<nav>
					<ul>
						<li>
							<%= link_to "Home", root_path %>
						</li>
						<li>
							<%= link_to "Secret", secret_path %>
						</li>
					</ul>
				</nav>
			</footer>
			<%= debug(params) if Rails.env.development? %>
		</div>
		<%= javascript_include_rpx(user_session_url) %>
	</body>
</html>

app/views/pages/home.html.erb
<h1>AuthTest</h1>
<p>This is the home of AuthTest.</p>

<%= embed_rpx user_session_url unless user_signed_in? %>

app/views/pages/secret.html.erb
<h1>The Secret Page</h1>
<p>This is the secret page.</p>